#!/usr/bin/ansible-playbook
- name: WeCreateHolidays deploy playbook
  hosts: env_{{ envType }}
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Checking Connection via Ping
      ping:

    - name: Installing apache 
      dnf:
        name: httpd
        state: latest

    - name: Ensure apache is running
      service:
        name: httpd
        state: started

    - name: Copy webapp
      copy:
        src: ../webapp/
        dest: /var/www/html